config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  root to: "home#index"

  resources :rooms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :room
  belongs_to :user
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  has_many :rooms
  has_one_attached :avatar
  has_many :bookings
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  def index
    @booking = Booking.all
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = current_user.bookings.build (booking_params)
    if @booking.save
      redirect_to @booking, notice: "Booking was successfully created"
    else
      render :new
      flash.now[:alert] = "Unable to create booking. Please try again!"
    end
  end


  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = current_user.rooms.build(room_params)

    if @room.save
    redirect_to root_path, notice: "Room was successfully created"
    else
      render :new
      flash.now[:alert] = "Unable to create room. Please try again!"
    end

  end

  def show
  end

  def room_params
    params.require(:room).permit(:description, :home_type, :room_type, :address, :bedroom, :bathroom, :price, image: [] )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/bootstrap_icons_helper.rb
module BootstrapIconsHelper
  # refer https://icons.getbootstrap.com/
  def icon(icon, options = {})
    file = File.read("node_modules/bootstrap-icons/icons/#{icon}.svg")
    doc = Nokogiri::HTML::DocumentFragment.parse file
    svg = doc.at_css 'svg'
    if options[:class].present?
      svg['class'] += " " + options[:class]
    end
      doc.to_html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/bookings/index.html.erb
<h1>Bookings</h1>

app/views/bookings/new.html.erb
<h2>Create New Booking</h2><br>

<%= form_for @booking do |f| %>

<%= f.label :start_date %>
<%= f.datetime_field :start_date %>

%= f.label :end_date %>
<%= f.datetime_field :end_date %>

<%=f.submit %>

<% end %>

app/views/home/index.html.erb
<h1>Welcome to AirBnb</h1>

<% if !user_signed_in? %>

<%= link_to "Sign Up", new_user_registration_path, class:"btn btn-primary" %>
<%= link_to "Log In", new_user_session_path, class:"btn btn-secondary" %>



<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
    <%= render "shared/sidebar"%>
    <% end %>

    <%= render "shared/navbar"  %>
    <%= render "shared/flash" %>
    <div class="ap-lm"><%= yield %></div>
  </body>
</html>

app/views/rooms/edit.html.erb
<div class="container">

  <h2>Edit room</h2><br>

  <%= form_for @room do |f| %>

    <div class="mb-3">
      <%= f.label :image, class:"form-label" %>
      <%= f.file_field :image, class:"form-control", multiple: true %>
    </div>

    <div class="mb-3">
      <%= f.label :description, class:"form-label" %>
      <%= f.text_field :description, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :home_type, class:"form-label" %>
      <%= f.text_field :home_type, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :bedroom, class:"form-label" %>
      <%= f.number_field :bedroom, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :bathroom, class:"form-label" %>
      <%= f.number_field :bathroom, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :address, class:"form-label" %>
      <%= f.text_area :address, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :price, class:"form-label" %>
      <%= f.number_field :price, class:"form-control" %>
    </div>

    <%= f.submit  %>

  <% end %>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Rooms</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_room_path, class: 'btn btn-primary' do %>
    Add New Room
  <% end %>

  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>



          <th></th>

      </tr>
    </thead>

    <tbody>
      <% @rooms.each do |room| %>
        <%= content_tag :tr, id: dom_id(room), class: dom_class(room) do %>




            <td><%= link_to 'Show', room %></td>

        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<div class="container">

  <h2>Create New Room</h2><br>

  <%= form_for @room do |f| %>

    <div class="mb-3">
      <%= f.label :image, class:"form-label" %>
      <%= f.file_field :image, class:"form-control", multiple: true %>
    </div>

    <div class="mb-3">
      <%= f.label :description, class:"form-label" %>
      <%= f.text_field :description, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :home_type, class:"form-label" %>
      <%= f.text_field :home_type, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :bedroom, class:"form-label" %>
      <%= f.number_field :bedroom, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :bathroom, class:"form-label" %>
      <%= f.number_field :bathroom, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :address, class:"form-label" %>
      <%= f.text_area :address, class:"form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :price, class:"form-label" %>
      <%= f.number_field :price, class:"form-control" %>
    </div>

    <%= f.submit  %>

  <% end %>
</div>

app/views/shared/_flash.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/shared/_sidebar.html.erb
<div id="side-navv" class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
      <%= icon("bootstrap", class:"bi me-2", width:"40", height:"32") %>
      <span class="fs-4">AirBNbee</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link text-white" aria-current="page">
          <%= icon("house-door", class:"bi me-2", width:"16", height:"16") %>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <%= icon("speedometer2", class:"bi me-2", width:"16", height:"16") %>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <%= icon("table", class:"bi me-2", width:"16", height:"16") %>
          Orders
        </a>
      </li>
      <li>
        <a href="/rooms" class="nav-link text-white">
          <%= icon("grid", class:"bi me-2", width:"16", height:"16") %>
          Rooms
        </a>
      </li>
      <li>
        <a href="#" class="nav-link text-white">
          <%= icon("people", class:"bi me-2", width:"16", height:"16") %>
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
        <%= image_tag resource.avatar, width:"32", height:"32", class: "rounded-circle me-2" %>
        <strong>Hello, <%= current_user.name %>!</strong>
      </a>
      <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><%= link_to "Account", edit_user_registration_path, class:"dropdown-item" %></li>
        <li><hr class="dropdown-divider"></li>
        <li><%= link_to "Sign out", destroy_user_session_path, class:"dropdown-item", method: :delete  %></li>
      </ul>
    </div>
  </div>

app/views/shared/_sidebar2.html.erb
<div class="flex-shrink-0 p-3 bg-white" style="width: 280px;">
    <a href="/" class="d-flex align-items-center pb-3 mb-3 link-dark text-decoration-none border-bottom">
      <svg class="bi me-2" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-5 fw-semibold">Collapsible</span>
    </a>
    <ul class="list-unstyled ps-0">
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded" data-bs-toggle="collapse" data-bs-target="#home-collapse" aria-expanded="true">
          Home
        </button>
        <div class="collapse show" id="home-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Overview</a></li>
            <li><a href="#" class="link-dark rounded">Updates</a></li>
            <li><a href="#" class="link-dark rounded">Reports</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#dashboard-collapse" aria-expanded="false">
          Dashboard
        </button>
        <div class="collapse" id="dashboard-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">Overview</a></li>
            <li><a href="#" class="link-dark rounded">Weekly</a></li>
            <li><a href="#" class="link-dark rounded">Monthly</a></li>
            <li><a href="#" class="link-dark rounded">Annually</a></li>
          </ul>
        </div>
      </li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#orders-collapse" aria-expanded="false">
          Orders
        </button>
        <div class="collapse" id="orders-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">New</a></li>
            <li><a href="#" class="link-dark rounded">Processed</a></li>
            <li><a href="#" class="link-dark rounded">Shipped</a></li>
            <li><a href="#" class="link-dark rounded">Returned</a></li>
          </ul>
        </div>
      </li>
      <li class="border-top my-3"></li>
      <li class="mb-1">
        <button class="btn btn-toggle align-items-center rounded collapsed" data-bs-toggle="collapse" data-bs-target="#account-collapse" aria-expanded="false">
          Account
        </button>
        <div class="collapse" id="account-collapse" style="">
          <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
            <li><a href="#" class="link-dark rounded">New...</a></li>
            <li><a href="#" class="link-dark rounded">Profile</a></li>
            <li><a href="#" class="link-dark rounded">Settings</a></li>
            <li><a href="#" class="link-dark rounded">Sign out</a></li>
          </ul>
        </div>
      </li>
    </ul>
  </div>